### PR TITLE
use datepicker widget for datetime input

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
Any reasons for the version pins in buildout? They are all pinned in Plone 5.x too.

**Comment by keul** [comment]
@smcmahon any motivation why this is not merged?

**Comment by Robynstar** [comment]
Having a few issues with this on Plone 5.0.5, on two different instances:

1.  A date/time field added before you upgrade still doesn't use the widget

1. Un-checking the 'show time options' check-box has no effect (although it does on a field added before the upgrade)

**Comment by keul** [comment]
I found some issues on this branch when date field is not provided and not required (validator is still executed and fails).

I extended (and superseded) this PR in https://github.com/smcmahon/Products.PloneFormGen/pull/176

About @Robynstar  comments:

* I fixed note 2: show_hm check behavior has been restored
* About note 1: to fix this we need a migration step that change internal persistent widget from `Calendarwidget` to `DatetimeWidget` or `DateWidget`.

**Comment by mauritsvanrees** [comment]
Closing in favor of #176.

**Pull request closed without merging**
