### PR TITLE
Fix redundant fallback template value

### PR DESCRIPTION
**Pull request by zemm**
`|nothing` in conjunction with `structure` or `provider:` (not sure which)
caused `ContentProviderLookupError: archetypes.edit.beforefieldsets|nothing` error
for me in some cases while debugging broken `RichTextField`.
It seems that it might not be a valid syntax?

In any case, it seems to be redundant, since there is also
`tal:on-error="nothing"`, and subsequent equivalent
`tal:replace="provider:archetypes.edit.afterfieldsets"`
does not have it either.

### CODE REVIEW

**Comment by zemm** [comment]
The test seems to be failing because with `|nothing`, it rendered an empty `<div></div>` between the `<form name="edit_form"`... and `<div id="pfg-fieldwrapper">`, and now it's absent. This missing empty div seems to fail the test.

So the doctest ellipses seem to require something between the two elements:

```doctest
    ...<div class="pfg-form formid-testform">
        <form name="edit_form" method="post" enctype="multipart/form-data" class="fgBaseEditForm..." action="..." id="fg-base-edit">
    ...
            <div id="pfg-fieldwrapper">
```

Not sure yet what would be an appropriate fix. I'll also recheck what the original error was, if I was mistaken, and why does it work most of the time.

**Comment by zemm** [comment]
Now after testing again, it seems that the actual problem might have been and is fixed by plone/Products.Archetypes#94, and the original error message pointed . This `|nothing` still seems like redundancy, but not that critical now.

**Comment by mauritsvanrees** [comment]
Somehow the actual problem that you found, causes this traceback that blames the provider. The traceback is basically lying, because it is not happening in those lines of the template.

But yes, removing the `|nothing` seems fine when I try it. It makes it the look the same as the `archetypes.edit.afterfieldsets` provider a few lines down.

**Comment by mauritsvanrees** [comment]
This fix is in release 1.8.4 (today).

**Pull request merged**
