### PR TITLE
Backport uninstall profile to 1.7.x

### PR DESCRIPTION
**Pull request by maethu**
I cherry-picked two commits:
- 8e9992e (Uninstall profile)
- c463a82 (Fix for uninstall function)

Further I implemented the removal of the actionicon from PloneFormGen using the uninstall function, since the GS actionicons.xml did not work for all plone 4.3.x versions.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Can you rebase your changes on the 1.7-maintenance branch and try again? That should help for the Travis tests.

**Comment by djowett-ftw** [comment]
@mauritsvanrees @maethu is this good to go now?

**Comment by maethu** [comment]
IMHO it is 😊

**Comment by djowett-ftw** [comment]
Found 1 amendment - it's good to ensure we have GenericSetup >= 1.8.2 for `post_handler`

**Comment by mauritsvanrees** [comment]
Sorry for the wait.
I have released Products.PloneFormGen 1.7.26 with these changes.

**Comment by djowett-ftw** [comment]
> Sorry for the wait.
> I have released Products.PloneFormGen 1.7.26 with these changes.

No worries, thanks Maurits!

**Pull request merged**
