### PR TITLE
Jquery 1.9

### LINKED ISSUE #188: PFG 1.7.x not compatible with jQuery 1.9+
due to $.live calls ... can we remove them in 1.7-maintenance branch?

### PR DESCRIPTION
**Pull request by petschki**
Fixes #188

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Thank you. Seems mostly okay.
But it does not completely work for me. I used the buildout in the package.

Scenario:
- Create a form.
- Go to the quick edit page.
- Drag a field (I tried with a Date/Time Field and also a String Field) to the form.
- Fill in a name and press Save.

Expected (behavior on 1.7-maintenance branch):
- The field is included in the form without doing a page reload.

Got (with your branch):
- I end up on the view of the new field.

So the click on the Save button is not caught. Can you look at that?

BTW, you have three commits which partial undo each other, so can you squash the commits into one commit for clarity? I don't know how great your git skills are, so if that is difficult: never mind, I can handle it.

**Comment by petschki** [comment]
ups ... have to check out why. I'm using Plone 4.3 and p.a.widgets 1.9 with PFG ... I'll try with the package buildout later on ...

**Comment by petschki** [comment]
@mauritsvanrees sorry for the delay ... I've fixed the .delegate() calls and squashed the commits together ... behavior is now as expected ...

**Comment by mauritsvanrees** [comment]
Looks, good, thanks!

**Comment by mauritsvanrees** [comment]
I have released 1.7.22 with this.

**Pull request merged**
