### PR TITLE
Remove collective.cover adapter reference

### LINKED ISSUE #194: Remove collective.cover adapter
We are removing the collective.cover adapter as it don't make sense anymore, and need to remove the reference inserted in this package.

### PR DESCRIPTION
**Pull request by rodfersou**
closes #194

### CODE REVIEW

**Comment by rodfersou** [comment]
@smcmahon I don't know why tests are failing..

These changes into next release will be really appreciated.

**Comment by rodfersou** [comment]
@smcmahon I don't know why tests are failing..

These changes into next release will be really appreciated.

**Comment by mauritsvanrees** [comment]
Sigh, Travis fails during bootstrapping again. Let's first fix that. I opened https://github.com/smcmahon/Products.PloneFormGen/pull/197 for that.
Other than that, looks good to me.

**Comment by mauritsvanrees** [comment]
@rodfersou Could you rebase? The tests should be green then.

**Comment by rodfersou** [comment]
@mauritsvanrees rebased

**Pull request merged**
